{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Process images"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from os.path import exists\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import cv2\n",
    "\n",
    "# Import function to extract features\n",
    "from extract_features import  process_images\n",
    "\n",
    "#-------------------\n",
    "# Main script\n",
    "#-------------------\n",
    "\n",
    "# Defining paths to metadata, images and their masks\n",
    "file_data = '..' + os.sep + 'data' + os.sep + 'metadata.csv'\n",
    "path_image = '..' + os.sep + 'data' + os.sep + 'images' + os.sep + 'images_train'\n",
    "path_mask = '..' + os.sep + 'data' + os.sep + 'images' + os.sep + 'masks_train'    \n",
    "\n",
    "# Defining the path to store the features\n",
    "file_features = 'features/features_original.csv'\n",
    "feature_names = ['assymetry', 'colours', 'dots and globules', 'compactness']\n",
    "\n",
    "#Processing images and saving annotations to csv\n",
    "df_features=process_images(file_data, path_image, path_mask,feature_names)\n",
    "df_features.to_csv(file_features, index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Train classifier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.\n",
      "  warnings.warn(\n",
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.\n",
      "  warnings.warn(\n",
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.\n",
      "  warnings.warn(\n",
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.\n",
      "  warnings.warn(\n",
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Classifier 1 (KNeighborsClassifier): average accuracy=0.518\n",
      "Classifier 2 (KNeighborsClassifier): average accuracy=0.552\n",
      "Classifier 3 (RandomForestClassifier): average accuracy=0.520\n",
      "Classifier 4 (GradientBoostingClassifier): average accuracy=0.579\n",
      "Classifier 5 (AdaBoostClassifier): average accuracy=0.586\n",
      "Classifier 6 (DecisionTreeClassifier): average accuracy=0.523\n",
      "Classifier 7 (Pipeline): average accuracy=0.589\n",
      "Classifier 8 (Pipeline): average accuracy=0.494\n",
      "Classifier 9 (Pipeline): average accuracy=0.547\n",
      "Classifier 10 (GaussianNB): average accuracy=0.527\n",
      "Results for KNeighborsClassifier:\n",
      "Accuracy: 0.6751398068124047\n",
      "Results for RandomForestClassifier:\n",
      "Accuracy: 0.8540925266903915\n",
      "Results for GradientBoostingClassifier:\n",
      "Accuracy: 0.6670055922724962\n",
      "Results for AdaBoostClassifier:\n",
      "Accuracy: 0.6344687341128622\n",
      "Results for DecisionTreeClassifier:\n",
      "Accuracy: 0.8601931875953228\n",
      "Results for Pipeline:\n",
      "Accuracy: 0.4926283680732079\n",
      "Results for GaussianNB:\n",
      "Accuracy: 0.5277071682765633\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n",
      "c:\\Users\\tettret\\Downloads\\Anaconda\\Lib\\site-packages\\sklearn\\metrics\\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, f\"{metric.capitalize()} is\", len(result))\n"
     ]
    }
   ],
   "source": [
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.linear_model import LogisticRegression, SGDClassifier\n",
    "from sklearn.naive_bayes import GaussianNB\n",
    "\n",
    "#from sklearn.neural_network import MLPClassifier\n",
    "\n",
    "from sklearn.model_selection import GroupKFold\n",
    "from sklearn.metrics import accuracy_score, classification_report\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "import pickle\n",
    "\n",
    "\n",
    "\n",
    "metadata_df = pd.read_csv(file_data)\n",
    "\n",
    "#Merging created annotations with patiend details\n",
    "combined_df = df_features.merge(metadata_df[['img_id', 'diagnostic', 'patient_id']], left_on='image_id', right_on='img_id', how='left')\n",
    "if combined_df.isnull().values.any():\n",
    "    raise ValueError(\"NaN values detected after merge! Check the data integrity.\")\n",
    "\n",
    "# Preparing the dataset\n",
    "\n",
    "# X - features evaluation\n",
    "X = combined_df[feature_names].to_numpy() \n",
    "# Y - patient diagnistic assuming that 'BCC' , 'MEL' and 'SCC' are cancerous\n",
    "y = np.logical_or(combined_df['diagnostic'].values == 'BCC', combined_df['diagnostic'].values == 'MEL', combined_df['diagnostic'].values == 'SCC')\n",
    "patient_id = combined_df['patient_id'].values\n",
    "\n",
    "# Preparing cross-validation\n",
    "num_folds = 5\n",
    "group_kfold = GroupKFold(n_splits=num_folds)\n",
    "\n",
    "# Initializing classifiers\n",
    "classifiers = [\n",
    "    KNeighborsClassifier(1), #classifier 0\n",
    "    KNeighborsClassifier(5), #classifier 1\n",
    "    RandomForestClassifier(n_estimators=100, random_state=42), #classifier 2\n",
    "    GradientBoostingClassifier(n_estimators=100, random_state=42), #classifier 3\n",
    "    AdaBoostClassifier(n_estimators=100, random_state=42), #classifier 4\n",
    "    DecisionTreeClassifier(random_state=42), #classifier 5\n",
    "    make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000)), #classifier 6\n",
    "    make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000, class_weight='balanced')), #classifier 7\n",
    "    make_pipeline(StandardScaler(), SGDClassifier(max_iter=1000, tol=1e-3)), #classifier 8\n",
    "    GaussianNB() #classifier 9\n",
    "]\n",
    "\n",
    "# Initializing accuracy storage\n",
    "acc_val = np.empty((num_folds, len(classifiers)))\n",
    "classifier_names = []\n",
    "\n",
    "# Performing cross-validation\n",
    "for j, clf in enumerate(classifiers):\n",
    "    classifier_name = (clf.named_steps['svc'].__class__.__name__ if 'pipeline' in str(clf)\n",
    "                       else clf.__class__.__name__)\n",
    "    classifier_names.append(classifier_name)\n",
    "    fold_accuracies = []\n",
    "    \n",
    "    for i, (train_index, val_index) in enumerate(group_kfold.split(X, y, patient_id)):\n",
    "        x_train, y_train = X[train_index], y[train_index]\n",
    "        x_val, y_val = X[val_index], y[val_index]\n",
    "        \n",
    "        # Fit and predict\n",
    "        clf.fit(x_train, y_train)\n",
    "        y_pred = clf.predict(x_val)\n",
    "        acc = accuracy_score(y_val, y_pred)\n",
    "        fold_accuracies.append(acc)\n",
    "        \n",
    "        # Save the classifier after training on this fold\n",
    "        fold_filename = f'classifier_{j}_fold_{i}.sav'\n",
    "        pickle.dump(clf, open(fold_filename, 'wb'))\n",
    "    \n",
    "    acc_val[:, j] = fold_accuracies\n",
    "\n",
    "# Calculating average accuracy for each classifier\n",
    "average_acc = np.mean(acc_val, axis=0)\n",
    "for idx, acc in enumerate(average_acc):\n",
    "    print(f'Classifier {idx + 1} ({classifier_names[idx]}): average accuracy={acc:.3f}')\n",
    "\n",
    "# Saving and evaluating each classifier on the full dataset\n",
    "eval_results = {}\n",
    "for idx, clf in enumerate(classifiers):\n",
    "\n",
    "    classifier_name = classifier_names[idx]\n",
    "    classifier_filename = f'classifier_{idx}.sav'\n",
    "    \n",
    "    # Saving the classifier\n",
    "    pickle.dump(clf, open(classifier_filename, 'wb'))\n",
    "    \n",
    "    # Load the classifier\n",
    "    loaded_clf = pickle.load(open(classifier_filename, 'rb'))\n",
    "    \n",
    "    # Predict on the full dataset and calculate evaluation metrics\n",
    "    y_pred = loaded_clf.predict(X)\n",
    "    acc = accuracy_score(y, y_pred)\n",
    "    clf_report = classification_report(y, y_pred)\n",
    "    \n",
    "    eval_results[classifier_name] = {'accuracy': acc, 'report': clf_report}\n",
    "\n",
    "# Display evaluation results\n",
    "for clf_name, results in eval_results.items():\n",
    "    print(f\"Results for {clf_name}:\")\n",
    "    print(f\"Accuracy: {results['accuracy']}\")\n",
    "    #print(f\"Classification Report:\\n{results['report']}\\n\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Evaluate classifier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded classifier from classifier_0.sav\n",
      "Results for classifier_0.sav:\n",
      "Accuracy: 0.4566929133858268\n",
      "Confusion Matrix:\n",
      " [[35 42]\n",
      " [27 23]]\n",
      "Loaded classifier from classifier_1.sav\n",
      "Results for classifier_1.sav:\n",
      "Accuracy: 0.5511811023622047\n",
      "Confusion Matrix:\n",
      " [[49 28]\n",
      " [29 21]]\n",
      "Loaded classifier from classifier_2.sav\n",
      "Results for classifier_2.sav:\n",
      "Accuracy: 0.4330708661417323\n",
      "Confusion Matrix:\n",
      " [[35 42]\n",
      " [30 20]]\n",
      "Loaded classifier from classifier_3.sav\n",
      "Results for classifier_3.sav:\n",
      "Accuracy: 0.5748031496062992\n",
      "Confusion Matrix:\n",
      " [[63 14]\n",
      " [40 10]]\n",
      "Loaded classifier from classifier_4.sav\n",
      "Results for classifier_4.sav:\n",
      "Accuracy: 0.5826771653543307\n",
      "Confusion Matrix:\n",
      " [[63 14]\n",
      " [39 11]]\n",
      "Loaded classifier from classifier_5.sav\n",
      "Results for classifier_5.sav:\n",
      "Accuracy: 0.4566929133858268\n",
      "Confusion Matrix:\n",
      " [[40 37]\n",
      " [32 18]]\n",
      "Loaded classifier from classifier_6.sav\n",
      "Results for classifier_6.sav:\n",
      "Accuracy: 0.6062992125984252\n",
      "Confusion Matrix:\n",
      " [[77  0]\n",
      " [50  0]]\n",
      "Loaded classifier from classifier_7.sav\n",
      "Results for classifier_7.sav:\n",
      "Accuracy: 0.49606299212598426\n",
      "Confusion Matrix:\n",
      " [[16 61]\n",
      " [ 3 47]]\n",
      "Loaded classifier from classifier_8.sav\n",
      "Results for classifier_8.sav:\n",
      "Accuracy: 0.5196850393700787\n",
      "Confusion Matrix:\n",
      " [[34 43]\n",
      " [18 32]]\n",
      "Loaded classifier from classifier_9.sav\n",
      "Results for classifier_9.sav:\n",
      "Accuracy: 0.44881889763779526\n",
      "Confusion Matrix:\n",
      " [[24 53]\n",
      " [17 33]]\n",
      "An error occurred while loading the model from classifier_10.sav: [Errno 2] No such file or directory: 'classifier_10.sav'\n",
      "Results for classifier_10.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_11.sav: [Errno 2] No such file or directory: 'classifier_11.sav'\n",
      "Results for classifier_11.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_12.sav: [Errno 2] No such file or directory: 'classifier_12.sav'\n",
      "Results for classifier_12.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_13.sav: [Errno 2] No such file or directory: 'classifier_13.sav'\n",
      "Results for classifier_13.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_14.sav: [Errno 2] No such file or directory: 'classifier_14.sav'\n",
      "Results for classifier_14.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_15.sav: [Errno 2] No such file or directory: 'classifier_15.sav'\n",
      "Results for classifier_15.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_16.sav: [Errno 2] No such file or directory: 'classifier_16.sav'\n",
      "Results for classifier_16.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_17.sav: [Errno 2] No such file or directory: 'classifier_17.sav'\n",
      "Results for classifier_17.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_18.sav: [Errno 2] No such file or directory: 'classifier_18.sav'\n",
      "Results for classifier_18.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_19.sav: [Errno 2] No such file or directory: 'classifier_19.sav'\n",
      "Results for classifier_19.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_20.sav: [Errno 2] No such file or directory: 'classifier_20.sav'\n",
      "Results for classifier_20.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_21.sav: [Errno 2] No such file or directory: 'classifier_21.sav'\n",
      "Results for classifier_21.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_22.sav: [Errno 2] No such file or directory: 'classifier_22.sav'\n",
      "Results for classifier_22.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_23.sav: [Errno 2] No such file or directory: 'classifier_23.sav'\n",
      "Results for classifier_23.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_24.sav: [Errno 2] No such file or directory: 'classifier_24.sav'\n",
      "Results for classifier_24.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_25.sav: [Errno 2] No such file or directory: 'classifier_25.sav'\n",
      "Results for classifier_25.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_26.sav: [Errno 2] No such file or directory: 'classifier_26.sav'\n",
      "Results for classifier_26.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_27.sav: [Errno 2] No such file or directory: 'classifier_27.sav'\n",
      "Results for classifier_27.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_28.sav: [Errno 2] No such file or directory: 'classifier_28.sav'\n",
      "Results for classifier_28.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_29.sav: [Errno 2] No such file or directory: 'classifier_29.sav'\n",
      "Results for classifier_29.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_30.sav: [Errno 2] No such file or directory: 'classifier_30.sav'\n",
      "Results for classifier_30.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_31.sav: [Errno 2] No such file or directory: 'classifier_31.sav'\n",
      "Results for classifier_31.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_32.sav: [Errno 2] No such file or directory: 'classifier_32.sav'\n",
      "Results for classifier_32.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_33.sav: [Errno 2] No such file or directory: 'classifier_33.sav'\n",
      "Results for classifier_33.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_34.sav: [Errno 2] No such file or directory: 'classifier_34.sav'\n",
      "Results for classifier_34.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_35.sav: [Errno 2] No such file or directory: 'classifier_35.sav'\n",
      "Results for classifier_35.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_36.sav: [Errno 2] No such file or directory: 'classifier_36.sav'\n",
      "Results for classifier_36.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_37.sav: [Errno 2] No such file or directory: 'classifier_37.sav'\n",
      "Results for classifier_37.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_38.sav: [Errno 2] No such file or directory: 'classifier_38.sav'\n",
      "Results for classifier_38.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_39.sav: [Errno 2] No such file or directory: 'classifier_39.sav'\n",
      "Results for classifier_39.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_40.sav: [Errno 2] No such file or directory: 'classifier_40.sav'\n",
      "Results for classifier_40.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_41.sav: [Errno 2] No such file or directory: 'classifier_41.sav'\n",
      "Results for classifier_41.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_42.sav: [Errno 2] No such file or directory: 'classifier_42.sav'\n",
      "Results for classifier_42.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_43.sav: [Errno 2] No such file or directory: 'classifier_43.sav'\n",
      "Results for classifier_43.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_44.sav: [Errno 2] No such file or directory: 'classifier_44.sav'\n",
      "Results for classifier_44.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_45.sav: [Errno 2] No such file or directory: 'classifier_45.sav'\n",
      "Results for classifier_45.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_46.sav: [Errno 2] No such file or directory: 'classifier_46.sav'\n",
      "Results for classifier_46.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_47.sav: [Errno 2] No such file or directory: 'classifier_47.sav'\n",
      "Results for classifier_47.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_48.sav: [Errno 2] No such file or directory: 'classifier_48.sav'\n",
      "Results for classifier_48.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_49.sav: [Errno 2] No such file or directory: 'classifier_49.sav'\n",
      "Results for classifier_49.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_50.sav: [Errno 2] No such file or directory: 'classifier_50.sav'\n",
      "Results for classifier_50.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_51.sav: [Errno 2] No such file or directory: 'classifier_51.sav'\n",
      "Results for classifier_51.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_52.sav: [Errno 2] No such file or directory: 'classifier_52.sav'\n",
      "Results for classifier_52.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_53.sav: [Errno 2] No such file or directory: 'classifier_53.sav'\n",
      "Results for classifier_53.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_54.sav: [Errno 2] No such file or directory: 'classifier_54.sav'\n",
      "Results for classifier_54.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_55.sav: [Errno 2] No such file or directory: 'classifier_55.sav'\n",
      "Results for classifier_55.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_56.sav: [Errno 2] No such file or directory: 'classifier_56.sav'\n",
      "Results for classifier_56.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_57.sav: [Errno 2] No such file or directory: 'classifier_57.sav'\n",
      "Results for classifier_57.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_58.sav: [Errno 2] No such file or directory: 'classifier_58.sav'\n",
      "Results for classifier_58.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_59.sav: [Errno 2] No such file or directory: 'classifier_59.sav'\n",
      "Results for classifier_59.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_60.sav: [Errno 2] No such file or directory: 'classifier_60.sav'\n",
      "Results for classifier_60.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_61.sav: [Errno 2] No such file or directory: 'classifier_61.sav'\n",
      "Results for classifier_61.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_62.sav: [Errno 2] No such file or directory: 'classifier_62.sav'\n",
      "Results for classifier_62.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_63.sav: [Errno 2] No such file or directory: 'classifier_63.sav'\n",
      "Results for classifier_63.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_64.sav: [Errno 2] No such file or directory: 'classifier_64.sav'\n",
      "Results for classifier_64.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_65.sav: [Errno 2] No such file or directory: 'classifier_65.sav'\n",
      "Results for classifier_65.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_66.sav: [Errno 2] No such file or directory: 'classifier_66.sav'\n",
      "Results for classifier_66.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n",
      "An error occurred while loading the model from classifier_67.sav: [Errno 2] No such file or directory: 'classifier_67.sav'\n",
      "Results for classifier_67.sav:\n",
      "Accuracy: None\n",
      "Confusion Matrix:\n",
      " None\n"
     ]
    }
   ],
   "source": [
    "import pickle\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix\n",
    "import glob\n",
    "\n",
    "#Defining path to metadata and testing set\n",
    "file_data = '..' + os.sep + 'data' + os.sep + 'metadata.csv'\n",
    "path_image = '..' + os.sep + 'data' + os.sep + 'images' + os.sep + 'images_original'\n",
    "path_mask = '..' + os.sep + 'data' + os.sep + 'images' + os.sep + 'masks_original'    \n",
    "\n",
    "#Processing images\n",
    "features_df = process_images(file_data, path_image, path_mask,feature_names)\n",
    "feature_names = ['assymetry', 'colours', 'dots and globules', 'compactness']\n",
    "\n",
    "# Merging features with metadata \n",
    "combined_df = features_df.merge(metadata_df[['img_id', 'diagnostic', 'patient_id']], left_on='image_id', right_on='img_id', how='left')\n",
    "\n",
    "# Preparing the dataset\n",
    "X = combined_df[feature_names].to_numpy()\n",
    "y = np.logical_or(combined_df['diagnostic'].values == 'BCC', combined_df['diagnostic'].values == 'MEL', combined_df['diagnostic'].values == 'SCC')\n",
    "\n",
    "patient_id = combined_df['patient_id']\n",
    "\n",
    "# Function to load a classifier and evaluate it\n",
    "def load_and_evaluate(model_filename, X, y):\n",
    "    try:\n",
    "        with open(model_filename, 'rb') as model_file:\n",
    "            classifier = pickle.load(model_file)\n",
    "        print(f\"Loaded classifier from {model_filename}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred while loading the model from {model_filename}: {e}\")\n",
    "        return None, None\n",
    "\n",
    "    # Predicting the labels and calculate accuracy and confusion matrix\n",
    "    pred_labels = classifier.predict(X)\n",
    "    accuracy = accuracy_score(y, pred_labels)\n",
    "    cm = confusion_matrix(y, pred_labels)\n",
    "    \n",
    "    return accuracy, cm\n",
    "\n",
    "# List of classifier filenames\n",
    "classifier_filenames = [f'classifier_{i}.sav' for i in range(len(os.listdir(r\"C:\\Users\\tettret\\OneDrive - DFDS\\Desktop\\ITU\\Data Science Project\\Project_data_science_queen_snakes-3\\Classifier_final\\Classifier\\fyp2024\")))]\n",
    "#model_filename=r\"C:\\Users\\tettret\\OneDrive - DFDS\\Desktop\\ITU\\Data Science Project\\Project_data_science_queen_snakes-3\\Classifier_final\\Classifier\\fyp2024\\classifier_3.sav\"\n",
    "#classifier_filenames = glob.glob(os.path.join('..', '*.sav'))\n",
    "\n",
    "# Evaluate all classifiers\n",
    "for model_filename in classifier_filenames:\n",
    "    accuracy, cm = load_and_evaluate(model_filename, X, y)\n",
    "    print(f\"Results for {model_filename}:\")\n",
    "    print(\"Accuracy:\", accuracy)\n",
    "    print(\"Confusion Matrix:\\n\", cm)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Evaluating classifier with more beautiful confusion matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.metrics import accuracy_score, confusion_matrix\n",
    "import glob\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "#Defining path to metadata and testing set\n",
    "data_dir = os.path.join('..', 'data')\n",
    "features_path = os.path.join(data_dir, 'metadata.csv')\n",
    "path_image = os.path.join(data_dir, 'images', 'images_original')\n",
    "path_mask = os.path.join(data_dir, 'images', 'masks_original')\n",
    "\n",
    "feature_names = ['assymetry', 'colours', 'dots and globules', 'compactness']\n",
    "features_df = process_images(features_path, path_image, path_mask, feature_names)\n",
    "\n",
    "# Loading metadata\n",
    "metadata_df = pd.read_csv(features_path)\n",
    "combined_df = features_df.merge(metadata_df[['img_id', 'diagnostic', 'patient_id']], left_on='image_id', right_on='img_id', how='left')\n",
    "\n",
    "# Defining the target variable 'y' where '1' represents cancerous conditions and '0' represents non-cancerous conditions\n",
    "cancerous_conditions = ['BCC', 'MEL', 'SCC']\n",
    "combined_df['target'] = combined_df['diagnostic'].apply(lambda x: 1 if x in cancerous_conditions else 0)\n",
    "y = combined_df['target'].values\n",
    "X = combined_df[feature_names].values\n",
    "patient_id = combined_df['patient_id']\n",
    "\n",
    "def load_and_evaluate(model_filename, X, y):\n",
    "    try:\n",
    "        with open(model_filename, 'rb') as model_file:\n",
    "            classifier = pickle.load(model_file)\n",
    "        print(f\"Loaded classifier from {model_filename}\")\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred while loading the model from {model_filename}: {e}\")\n",
    "        return None, None\n",
    "\n",
    "    pred_labels = classifier.predict(X)\n",
    "    accuracy = accuracy_score(y, pred_labels)\n",
    "    cm = confusion_matrix(y, pred_labels)\n",
    "\n",
    "    # Plot the confusion matrix\n",
    "    plt.figure(figsize=(8, 6))\n",
    "    sns.heatmap(cm, annot=True, fmt='g', cmap='Blues', cbar=False,\n",
    "                xticklabels=['Non-cancerous', 'Cancerous'],\n",
    "                yticklabels=['Non-cancerous', 'Cancerous'])\n",
    "    plt.xlabel('Predicted labels')\n",
    "    plt.ylabel('True labels')\n",
    "    plt.title('Confusion Matrix')\n",
    "    plt.show()\n",
    "    \n",
    "    return accuracy, cm\n",
    "\n",
    "# Using glob to find all classifier files\n",
    "classifier_dir = r\"C:\\Data Science project files\\Classifier\\fyp2024\"\n",
    "classifier_filenames = glob.glob(os.path.join(classifier_dir, '*.sav'))\n",
    "\n",
    "# Evaluating all classifiers\n",
    "for model_filename in classifier_filenames:\n",
    "    accuracy, cm = load_and_evaluate(model_filename, X, y)\n",
    "    if accuracy is not None:\n",
    "        print(f\"Results for {model_filename}:\")\n",
    "        print(\"Accuracy:\", accuracy)\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Output probabilities"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded classifier from classifier_7.sav\n",
      "Predictions have been saved to predictions_new.xlsx\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import glob\n",
    "from extract_features import  process_images\n",
    "\n",
    "data_dir = os.path.join('..', 'data')\n",
    "features_path = os.path.join(data_dir, 'metadata.csv')\n",
    "path_image = os.path.join(data_dir, 'images', 'images_original')\n",
    "path_mask = os.path.join(data_dir, 'images', 'masks_original')\n",
    "\n",
    "#Define features to use in classification\n",
    "feature_names = ['assymetry', 'colours', 'dots and globules', 'compactness']\n",
    "features_df = process_images(features_path, path_image, path_mask, feature_names)\n",
    "\n",
    "# Load metadata\n",
    "metadata_df = pd.read_csv(features_path)\n",
    "combined_df = features_df.merge(metadata_df[['img_id', 'diagnostic', 'patient_id']], left_on='image_id', right_on='img_id', how='left')\n",
    "\n",
    "# Define the target variable 'y' where '1' represents cancerous conditions and '0' represents non-cancerous conditions\n",
    "cancerous_conditions = ['BCC', 'MEL', 'SCC']\n",
    "combined_df['target'] = combined_df['diagnostic'].apply(lambda x: 1 if x in cancerous_conditions else 0)\n",
    "\n",
    "# Load model and predict probabilities\n",
    "def predict_probabilities(model_filename, X):\n",
    "    try:\n",
    "        with open(model_filename, 'rb') as model_file:\n",
    "            classifier = pickle.load(model_file)\n",
    "        print(f\"Loaded classifier from {model_filename}\")\n",
    "        probabilities = classifier.predict_proba(X)\n",
    "        return probabilities\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred while loading the model: {e}\")\n",
    "        return None\n",
    "\n",
    "#Define pass to the model \n",
    "model_filename = r\"classifier_7.sav\"\n",
    "\n",
    "\n",
    "# Create a list to save probabilities with patient id and labels\n",
    "results = []\n",
    "\n",
    "probabilities = predict_probabilities(model_filename, features_df[feature_names].values)\n",
    "if probabilities is not None:\n",
    "    # Iterate over each prediction and corresponding image ID\n",
    "    for idx, prob in enumerate(probabilities):\n",
    "        results.append({\n",
    "            'Patient ID': combined_df.iloc[idx]['patient_id'],\n",
    "            'Image ID': features_df.iloc[idx]['image_id'],\n",
    "            'Probability Non-cancerous': prob[0],  # Assuming 0 is non-cancerous\n",
    "            'Probability Cancerous': prob[1],     # Assuming 1 is cancerous\n",
    "            'Actual Label': combined_df.iloc[idx]['target']  # Ensure target column exists\n",
    "        })\n",
    "\n",
    "# Create a DataFrame from results\n",
    "results_df = pd.DataFrame(results)\n",
    "\n",
    "# Define the Excel writer and the path for the Excel file\n",
    "excel_path = 'predictions_new.xlsx'\n",
    "\n",
    "\n",
    "# Write DataFrame to an Excel file\n",
    "results_df.to_excel(excel_path, index=False)\n",
    "\n",
    "\n",
    "print(f\"Predictions have been saved to {excel_path}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
